---
title: "Econ Games"
---

### Macroeconomics Monetary and Fiscal Policy Simulation Game
Created by Valentinas Rudys

- Supplementary Learning Tool for advanced high school economics classes
- Supplementary Learning Tool for Introductory and Intermediate Macroeconomics college courses

- Description of the Game
- Learning Outcomes
- Assessment and Performance Reports

- Short Introductory Video
- Demo Version of the Game

\


### Microeconomics Business Simulation Game
In progress. Author: Valentinas Rudys

- Supplementary Learning Tool for advanced high school economics classes
- Supplementary Learning Tool for Introductory and Intermediate Microeconomics college courses

- Description of the Game
- Learning Outcomes
- Assessment and Performance Reports

- Short Introductory Video
- Demo Version of the Game

\


### Business Strategy Simulation Game
In progress. Author: Valentinas Rudys

- Supplementary Learning Tool for Intermediate to Advanced Business Management and Strategy college courses
- Supplementary Learning Tool for College of Business Capstone courses

- Description of the Game
- Learning Outcomes
- Assessment and Performance Reports

- Short Introductory Video
- Demo Version of the Game

\


> [Provide Annonymous Feedback](https://docs.google.com/forms/d/e/1FAIpQLSdAtAn3hsF1Cfy84sgsYFyeOwRvReJGHzFDDucIKL3EYQyfZA/viewform?usp=pp_url)



