---
title: "Infinitely-Lived Heterogeneous Agent Model"
---

Matlab function [[download](models/infitite_het_agents.m)]

<pre class="codeinput">clearvars
tic <span class="comment">%start timer</span>
<span class="comment">%Set parameters for Markov approximation of labor shocks</span>
rho=.3;<span class="comment">%persistence parameter for labor shocks</span>
sigma=.2; <span class="comment">%standard deviation of labor shocks</span>
m=3; <span class="comment">%number of standard deviations from mean</span>
mul=1; <span class="comment">%mean for labor shocks</span>
states=7; <span class="comment">%number of possible states for labor shocks</span>
[Z,Zprob] = tauchen(states,mul,rho,sigma,m);
P=Zprob;<span class="comment">%transition matrix</span>
z=Z';<span class="comment">%possible values for labor shocks</span>
alpha=.36;<span class="comment">%production parameter</span>
MU=3;<span class="comment">%degree of risk aversion</span>
step=.2; <span class="comment">%step size between capital grid</span>
beta=.96;<span class="comment">%discount factor</span>
delta=.08;<span class="comment">%depreciation</span>
lambda=(1-beta)/beta;<span class="comment">%time discount rate</span>
it=1;<span class="comment">%initialize counter</span>
warning <span class="string">off</span> <span class="string">all</span>
Zinv=Zprob^100;
<span class="comment">%%%%%%%%%%% Step One %%%%%%%%%%</span>
N0=sum(z.*Zinv(1,:));<span class="comment">%stationary employment</span>
<span class="comment">%%%%%%%%%%% Step Two %%%%%%%%%%</span>
K0=5.6; <span class="comment">%guess at initial capital stock</span>

DifK=1;
ik=0;
<span class="keyword">while</span> DifK&gt;1.01 <span class="comment">%stopping criteria for aggregate capital stock</span>
    <span class="comment">%%%%%%%%%%% Step Three %%%%%%%%%%</span>
    w1=(1-alpha)*(K0/N0)^alpha;<span class="comment">%wage rate based on capital stock</span>
    r=(alpha)*(K0/N0)^(alpha-1)-delta<span class="comment">%interest rate based on capital stock</span>
    gridi=[-2:step:40]'; <span class="comment">% column i asset holdings grid</span>
    gridj=[-2:step:40]';<span class="comment">% column j asset holdings grid</span>
    v0=zeros(length(gridj),length(z));<span class="comment">%initialize value function</span>
    g0=zeros(length(gridj),length(z));<span class="comment">%initialize policy function</span>
    jgrid=length(gridj);
    dif=1;<span class="comment">%initialize differences</span>
    dif2=1;
    ik=ik+1;
    epsilon=.001;
    <span class="comment">%%%%%%%%%%% Step Four %%%%%%%%%%</span>
    display(<span class="string">'Performing Value Function Iteration'</span>)
    <span class="keyword">while</span> dif&gt;epsilon*(1-beta);<span class="comment">%stopping criteria for value function iteration</span>
        <span class="keyword">for</span> j=1:length(z);<span class="comment">%loop over possible labor shocks</span>
            <span class="keyword">parfor</span> i=1:length(gridi);<span class="comment">%loop over current asset states</span>
                c=(1+r).*gridi(i)+w1*z(j)-gridj;<span class="comment">%consumption</span>
                <span class="keyword">if</span> c(1)&lt;0;
                     c(1)=inf;
                     c=(c+.1).*(c&gt;=0);<span class="comment">%ensuring nonnegative consumption</span>
                <span class="keyword">else</span>
                     c=(c+.1).*(c&gt;=0);<span class="comment">%ensuring nonnegative consumption</span>
                <span class="keyword">end</span>
                w=(c.^(1-MU)-1)./(1-MU)+beta.*sum(repmat(P(j,:),length(v0),1).*v0,2);<span class="comment">%value function</span>
                wstar(i,j)=max(w);<span class="comment">%finding maximum of value function over grid choice for each state</span>
                jhold(i,j)=find(max(w)==w);<span class="comment">%pointer indicating position of maximum aprime</span>
                gprime(i,j)=gridj(jhold(i,j));<span class="comment">%optimal policy</span>
            <span class="keyword">end</span>;
        <span class="keyword">end</span>
        dif=max(max(abs(wstar-v0)));<span class="comment">%difference between value functions</span>
        dif1(it)=dif;<span class="comment">%storing difference between value functions</span>
        dif2=max(max(abs(g0-gprime)));<span class="comment">%difference between policy functions</span>
        policydif(it)=dif2;<span class="comment">%storing difference between policy functions</span>
        g0=gprime;<span class="comment">%update policy function</span>
        v0=wstar;<span class="comment">%update value function</span>
        it=it+1;<span class="comment">%update iteration counter</span>
    <span class="keyword">end</span>
    its=100;<span class="comment">%increase number of iterations over density function iteration each iteration over K</span>
    <span class="comment">%%%%%%%%%%% Step Five and Step Six %%%%%%%%%%</span>
    display(<span class="string">'Iterating on the distribution function'</span>)
    [f,K1,gridj2]=invarfpar(P,gridj,gprime,step,its);<span class="comment">%function that calculates invariant distribution</span>
    Kstore(ik)=K0<span class="comment">%storing aggregate capital over capital iterations</span>
    DifK=max(abs(K1-K0));<span class="comment">%calculating difference in aggregate capital</span>
    phi=.1;<span class="comment">%relaxation parameter for updating aggregate capital stock</span>
    <span class="comment">%%%%%%%%%%% Step Seven %%%%%%%%%%</span>
    K0=phi*K1+(1-phi)*K0;<span class="comment">%update aggregate capital stock</span>
    display(<span class="string">'Dif between r and lambda'</span>)
    r-lambda
    <span class="keyword">if</span> r-lambda&gt;0
        K0=unifrnd(5,9);
    <span class="keyword">else</span>
        K0=K0;
    <span class="keyword">end</span>
    DifKstore(ik)=DifK<span class="comment">%storing difference between aggregate capital iterations</span>
<span class="keyword">end</span>
K0=K1;
w1=(1-alpha)*(K0/N0)^alpha;<span class="comment">%wage based on final value of capital stock</span>
r=(alpha)*(K0/N0)^(alpha-1)-delta;<span class="comment">%interest rate based on final value of capital stock</span>
copt=(1+r).*repmat(gridj,1,length(z))+w1.*repmat(z,length(gridj),1)-gprime;<span class="comment">%policy function for consumption</span>
figure;plot(gridj,copt)
title(<span class="string">'Policy function for consumption'</span>); xlabel(<span class="string">'Current asset level'</span>)
ylabel(<span class="string">'Optimal Consumption'</span>); legend(<span class="string">'Low labor shock'</span>,<span class="string">'High labor shock'</span>)

figure;plot(gridj,gprime)
title(<span class="string">'Policy function for next periods asset'</span>); xlabel(<span class="string">'Current asset level'</span>)
ylabel(<span class="string">'Optimal next period asset'</span>); legend(<span class="string">'Low labor shock'</span>,<span class="string">'High labor shock'</span>)

display(<span class="string">'Savings Rate Without Full Insurance'</span>)
100*delta*alpha/(r+delta)
display(<span class="string">'Savings Rate With Full Insurance'</span>)
100*delta*alpha/(lambda+delta)

toc

<span class="keyword">function</span>[fx]=lininterp(fx1,fx2,x1,x2,x)
fx=fx1+((fx2-fx1)./(x2-x1)).*(x-x1);
<span class="keyword">end</span>

<span class="keyword">function</span>[f,muk,gridj2]=invarfpar(P,gridj,gprime,step,its);
n=size(P,1);
k=size(P,1);
step1=step/3;
gridj2=min(gridj):step1:max(gridj);
m=length(gridj2);
f1=zeros(m,n);
f2=f1;
f2(1,1)=1;
f0=(1/(m*n))*ones(m,n);
diff=1;
it=0;
nopt=length(gprime);
nk=length(gridj2);
<span class="keyword">while</span> it&lt;its
    it=it+1;
    <span class="keyword">for</span> k=1:n
        <span class="keyword">for</span> l=1:m
            k0=gridj2(l);
            <span class="keyword">if</span> k0&lt;=min(gridj2)
                aprime=gprime(1,:);
            <span class="keyword">elseif</span> k0&gt;=max(gridj2)
                aprime=gprime(nopt,:);
            <span class="keyword">else</span>
                ind=sum(gridj&lt;k0);
                x1=gridj(ind);
                x2=gridj(ind+1);
                fx1=gprime(ind,:);
                fx2=gprime(ind+1,:);
                aprime=lininterp(fx1,fx2,x1,x2,gridj2(l));
            <span class="keyword">end</span>
            kmin=sum(aprime&lt;=min(gridj2));
            kmax=sum(aprime&gt;=max(gridj2));
            <span class="keyword">if</span> kmin~=0
                krep=n-kmin;
                indc=find((aprime&lt;=min(gridj2))==1);
                ku=length(indc)+1;
                f1(1,[indc])=f1(1,[indc])+P(k,[indc]).*f0(l,k);
                i=sum((repmat(gridj2',1,n)&lt;=repmat(aprime,m,1)))+1;
                i=i(ku:n);
                n0=(aprime(ku:n)-gridj2(i-1))./(gridj2(i)-gridj2(i-1));
                kuind=ku:n;
                <span class="keyword">for</span> jk=1:length(i);
                    f1(i(jk),kuind(jk))=f1(i(jk),kuind(jk))+P(k,kuind(jk)).*n0(jk).*f0(l,k);
                    f1(i(jk)-1,kuind(jk))=f1(i(jk)-1,kuind(jk))+P(k,kuind(jk)).*(1-n0(jk)).*f0(l,k);
                <span class="keyword">end</span>
            <span class="keyword">elseif</span> kmax~=0
                ku=(n-kmax);
                indc=find((aprime&gt;=max(gridj2))==1);
                f1(nk,[indc])=f1(nk,[indc])+P(k,[indc]).*f0(l,k);
                i=sum((repmat(gridj2',1,n)&lt;=repmat(aprime,m,1)))+1;
                i=i(1:ku);
                n0=(aprime(1:ku)-gridj2(i-1))./(gridj2(i)-gridj2(i-1));
                kuind=1:ku;
                <span class="keyword">for</span> jk=1:length(i);
                    f1(i(jk),kuind(jk))=f1(i(jk),kuind(jk))+P(k,kuind(jk)).*n0(jk).*f0(l,k);
                    f1(i(jk)-1,kuind(jk))=f1(i(jk)-1,kuind(jk))+P(k,kuind(jk)).*(1-n0(jk)).*f0(l,k);
                <span class="keyword">end</span>
            <span class="keyword">else</span>
                i=sum((repmat(gridj2',1,n)&lt;=repmat(aprime,m,1)))+1;
                n0=(aprime-gridj2(i-1))./(gridj2(i)-gridj2(i-1));
                kuind=1:n;
                <span class="keyword">for</span> jk=1:n;
                    f1(i(jk),kuind(jk))=f1(i(jk),kuind(jk))+P(k,kuind(jk)).*n0(jk).*f0(l,k);
                    f1(i(jk)-1,kuind(jk))=f1(i(jk)-1,kuind(jk))+P(k,kuind(jk)).*(1-n0(jk)).*f0(l,k);
                <span class="keyword">end</span>
            <span class="keyword">end</span>
        <span class="keyword">end</span>
    <span class="keyword">end</span>
    f1=f1./sum(sum(f1));

    diff=sum(sum(abs(f1-f0)));
    difstore(it)=diff;
    f0=f1;
    diff;
<span class="keyword">end</span>
f=f1;
muk=sum(sum(repmat(gridj2',1,n).*f1));
<span class="keyword">end</span>

<span class="keyword">function</span> [Z,Zprob] = tauchen(N,mu,rho,sigma,m)
Z     = zeros(N,1);
Zprob = zeros(N,N);
a     = (1-rho)*mu;
Z(N)  = m * sqrt(sigma^2 / (1 - rho^2));
Z(1)  = -Z(N);
zstep = (Z(N) - Z(1)) / (N - 1);
<span class="keyword">for</span> i=2:(N-1)
    Z(i) = Z(1) + zstep * (i - 1);
<span class="keyword">end</span>
Z = Z + a / (1-rho);
<span class="keyword">for</span> j = 1:N
    <span class="keyword">for</span> k = 1:N
        <span class="keyword">if</span> k == 1
            Zprob(j,k) = cdf_normal((Z(1) - a - rho * Z(j) + zstep / 2) / sigma);
        <span class="keyword">elseif</span> k == N
            Zprob(j,k) = 1 - cdf_normal((Z(N) - a - rho * Z(j) - zstep / 2) / sigma);
        <span class="keyword">else</span>
            Zprob(j,k) = cdf_normal((Z(k) - a - rho * Z(j) + zstep / 2) / sigma) - <span class="keyword">...</span>
                         cdf_normal((Z(k) - a - rho * Z(j) - zstep / 2) / sigma);
        <span class="keyword">end</span>
    <span class="keyword">end</span>
<span class="keyword">end</span>
<span class="keyword">function</span> c = cdf_normal(x)
    c = 0.5 * erfc(-x/sqrt(2));
<span class="keyword">end</span>
<span class="keyword">end</span>
</pre>

<!-- R function [[download]()]
```{r, eval=FALSE}

```

Python function [[download](gss_bivariate.Py)]
```{python, eval=FALSE}

```
-->


<style type="text/css">
pre.codeinput { padding:10px; border:1px solid #d3d3d3; background:#f7f7f7; }
pre.codeoutput { padding:10px 11px; margin:0px 0px 20px; color:#4c4c4c; }
pre.error { color:red; }
@media print { pre.codeinput, pre.codeoutput { word-wrap:break-word; width:100%; } }
span.keyword { color:#0000FF }
span.comment { color:#228B22 }
span.string { color:#A020F0 }
span.untermstring { color:#B20000 }
span.syscmd { color:#B28C00 }
</style>