---
title: "Introduction to Popular Programming Languages"
output: flexdashboard::flex_dashboard
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
octaveExe <- Sys.getenv("C:/Octave/Octave-5.2.0/usr/bin")
octaveExe
```


<style>
.column {
  float: left;
  width: 33.33%;
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}
</style>

#### Simple Math Expressions



<div class="column">
```{r r1, engine='R'}
#in R
5+5
1+2/(1+3)
z<-10
z
x=1+2
x
y_1=5
y.2=11
y3=y_1+y.2
y3
```
</div>
<div class="column">
```{r p1, engine='python'}
#in Python
5+5
1+2/(1+3)
z=10
z
x=1+2
x
y_1=5
y_2=11
y3=y_1+y_2
y3
```
</div>
<div class="column">
```{octave}

#in Matlab
5+5
1+2/(1+3)
z=10
z
x=1+2
x
y_1=5
y.2=11
y3=y_1+y.2
y3
``` 
</div>


#### Saving and Calling Variables


```{r f2, engine.path="C:/Octave/Octave-5.2.0/usr/bin"}
#vectors in R
x=c(1,2,3,4,5)
x
y=seq(from=1,to=10,by=1)
y
#math with vectors in R
x/5
```

```{r r5, message=FALSE, warning=FALSE, cache=TRUE}
#matrix in R
m=matrix(seq(1,9,1),3,3)
m
#math with matrices in R
m=m+5
m
m*2
```

```{r r6, message=FALSE, warning=FALSE, cache=TRUE}
#matrix in R
m=matrix(seq(1,9,1),3,3)
#math with matrices in R
m=m+5
m
m*2
```

```{r r7, message=FALSE, warning=FALSE, cache=TRUE}
#indices in R
m[1,3]
m[1,]
m[,3]
```

```{r r8, message=FALSE, warning=FALSE, cache=TRUE}
#if else statement in R
a=-5
if (a>0){
  print("positive")
} else if (a==0){
  print("null")
} else {
  print("negative")
}
```

```{r r9, message=FALSE, warning=FALSE, cache=TRUE}
#for loop in R
a=matrix(0,3,3)
for (x in 1:9){
  a[x]=2*x-1
}
a  
```

```{r r10, message=FALSE, warning=FALSE, cache=TRUE}
#while loop in R
a=matrix(0,3,3)
x=0
while (x<10){
  a[x]=2*x-1
  x=x+1
}
a  
```

```{r r11, message=FALSE, warning=FALSE, cache=TRUE}
#creating functions in R
HeightConverter = function(height,inch_or_cm){
  if (inch_or_cm=="inches"){
    x=height/0.39370
    y="centimeters"
  } else if (inch_or_cm=="cm"){
    x=height*0.39370
    y="inches"
  }
  cat("Height of", height, "is equivalent to", round(x,1), y)
}
HeightConverter(75,"inches")
HeightConverter(190,"cm") 
```

---
