---
title: "Programming"
---


#### Intro to Programming Languages
- R
- Matlab/Octave
- Python
- SQL
- Julia
- Ruby
- C++/C#
- VBA

#### Original Code
- High-Frequency Trading
- linear algebra and vector manipulation
- Monte Carlo simulation, trinomial trees and finite differences.
- Data Mining
- Auto-regression
- Auto-correlation
- Principal Component Analysis
- Equity Long/Short experience with focus on Index Equity
- Machine Learning
- Non-parametric Econometrics
- Factor modeling
- Derivative pricing
- Understanding of equities portfolio construction, risk/return attribution, transaction cost analysis, and portfolio research, coupled with ability to view and react to live portfolios
- Bayesian optimization, stochastic modeling, 
- ML and NLP models for acquiring and analyzing proprietary unstructured textual data
- Portfolio optimization
- Reduced Form Causal Analysis?
- Experimental research 
- Relative value models for fixed income and interest rates derivatives
- systematic alpha research
- automated market making
- financial research and portfolio management.
- Domain knowledge in futures is a plus
- survey sampling and design, significance testing, regression modeling, experimental design, behavioral data analysis)
- GLM, analysis of quasi-experimental research designs with non-equivalent groups (e.g., regression adjustment, matching, propensity score stratification), longitudinal analysis, classification, dimension reduction, clustering, hierarchical linear (random effects) modeling, etc., to people research problems in organizations
- scikit-learn, Pandas, keras, and tensorflow
- Experience using MSCI’s Barra One or Risk Manager models for fixed income analysis/risk management and scenario analysis
- Experience using Bloomberg’s GRM or PORT models for fixed income analysis/risk management and scenario analysis
- ML/AI approaches, including classification, clustering, and regression
- Machine learning skills: Machine Learning techniques such as NLP, K means clustering, Neural Networks etc
- Systematic/High Frequency or Electronic Trading

