---
title: "Research"
---


### Working Papers:

 <hr>

#### Stylized Social Security Reforms with Labor Market Frictions (Job Market Paper)

-- Download: [Working Paper](Rudys_Paper_1_JMP.pdf), [One-Page Summary](One_Page_Summary___Paper_1.pdf)

**Abstract**: Social Security provides a large fraction of income to the elderly in the US. Shortfalls in the Social Security fund make reforms inevitable. I examine the effect of reforms using a novel overlapping generations model with search and matching labor market frictions. I find that new labor market
channels magnify the long-term beneficial outcomes of policies encouraging private saving and labor
force participation. A cut in benefits or increase in retirement age decreases equilibrium unemployment
via higher labor demand due to a fall in the interest rate, reduced job search slack, and a reinforcing
feedback effect between labor demand and supply.

 <hr>

#### Boosting Older Worker Employment. Analysis of Hiring and Wage Subsidies

-- Download: [One-Page Summary](One_Page_Summary___Paper_2.pdf)

**Abstract**: With longer expected lifetimes and a low median savings rate, an increasing number of elderly Americans will need to work past a typical current retirement age. This may be made more difficult by old age discrimination and various adverse employment shocks at old age such as Covid-19. Hiring subsidies for older workers are among the active labor market policies that could increase firms' demand of elderly labor. In a computable overlapping generations model with labor market frictions, I examine the long-term hiring subsidies absent of any shocks and the short-term hiring subsidies following an adverse elderly employment shock.

I find that when a long-term hiring subsidy is introduced, a firm replaces general vacancies with specific elderly-targeting vacancies. This allows an increase of elderly employment in the long run at a cost of lower employment of a workforce below the subsidy-protected age. This hiring subsidy does not increase overall demand for labor but simply shifts the demand from younger to older workers. As the elderly-protecting hiring subsidy increases, there is an increasingly distortionary effect on the youth employment causing an aggregate decrease in employment and large welfare losses no matter the financing of the subsidy. The results are equivalent when wage subsidy is used to increase elderly employment.

A short-term elderly-targeting hiring subsidy after an adverse shock to elderly employment has a positive consumption and welfare effects on multiple generations directly affected by the unexpected shock but, again, negatively affects the younger generations via distorted competition in the labor market. The negative effect on the younger cohorts also increase the time until full recovery to the steady state.

 <hr>

#### Hidden Labor Market and Active Labor Market Policies

-- Download: [One-Page Summary](One_Page_Summary___Paper_3.pdf)

Presented at The New York State Economic Association 71st Annual Conference (Fall, 2018)\
Presented at 2019 Eastern Economic Association (March, 2019)\
Presented at the 4th International ESS Conference (April, 2019)

**Abstract**: A non-trivial share of European labor force is employed informally, i.e. without contracts, or engage in informal self-employment. European Commission is aiming to reduce such employment and thus has founded European Platform Tackling Undeclared Work among other initiatives. In this paper, I identify patterns of uncontracted work in Europe and try to identify ways to reduce informal (undeclared) employment. More specifically, I ask if labor policies such as age-specific hiring subsidies and firing taxes could decrease informal employment?
		
Using European Social Survey (ESS), I show that (a) hidden labor market in European countries exhibits U-shape age profile, (b) hidden workers typically have experienced more recent and longer unemployment spells, and (c) while informal workers do not have significantly different work preferences, they receive a small but statistically significant informal wage penalty. 
		
Inspired by these findings, I set up a life-cycle search and matching model with informal work opportunities. I calibrate the model to United Kingdom, a Western European country with relatively high levels of informality among the old, and then consider how age-varying firing costs and hiring subsidies affect the composition of the informal and formal employment. As firms take into account current and future taxes and subsidies, they adjust their hiring and firing decisions. Simulations indicate that hiring subsidies create an incentive for a firm to increase turnover which may have a negative effect on formal employment and positive effect on informal employment. Firing taxes increase older worker retention but also reduce hiring. If the decrease in hiring is not as large as decrease in firing rate, such policy may have a positive effect on formal and negative effect on informal employment.

 <hr>

#### Portfolio Allocation and Retirement Income

-- Download: [One-Page Summary](One_Page_Summary___Paper_4.pdf)

**Abstract**: Portfolio allocation decisions over the lifecycle depend on the retirement income and risks faced in retirement. However, due to computational complexity, many features of retirement income are typically assumed away. By building on the standard lifecycle investment-consumption model that includes a realistic retirement income, I discuss how each aspect of retirement income affects optimal portfolio allocation over the lifecycle. I find that all investors maintain high levels of stocks in their portfolios at a young age. However, investors who face low net replacement rates, risk of forced retirement, or retirement income uncertainty, hedge these risks by accumulating higher private savings and reducing risky portfolio share at an earlier age. In a realistic setting with risks and endogenous retirement age, equity portfolio share temporarily increases once the investor becomes eligible for retirement.		

 <hr>

